# Generated by Django 5.1.5 on 2025-01-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="storage_images/", verbose_name="Фото"),
                ),
                ("city", models.CharField(max_length=255, verbose_name="Город")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                ("temperature", models.FloatField(verbose_name="Температура")),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Контакты"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=1024, verbose_name="Описание"
                    ),
                ),
                (
                    "directions",
                    models.CharField(blank=True, max_length=255, verbose_name="Проезд"),
                ),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
            },
        ),
    ]
