# Generated by Django 5.1.5 on 2025-01-21 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Номер бокса",
                    ),
                ),
                ("level", models.IntegerField(verbose_name="Этаж")),
                ("height", models.FloatField(verbose_name="Высота, м.")),
                ("width", models.FloatField(verbose_name="Ширина, м.")),
                ("length", models.FloatField(verbose_name="Длина, м.")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "is_occupied",
                    models.BooleanField(default=False, verbose_name="Занята"),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxes",
                        to="storage.storage",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бокс",
                "verbose_name_plural": "Боксы",
            },
        ),
    ]
