# Generated by Django 5.1.5 on 2025-01-22 07:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_box"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата начала аренды",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(verbose_name="Дата окончания аренды"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("active", "Активна"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                            ("expired", "Просрочена"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Статус аренды",
                    ),
                ),
                (
                    "pickup_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Адрес забора груза",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Общая сумма аренды",
                    ),
                ),
                (
                    "is_delivery_needed",
                    models.BooleanField(verbose_name="Нужна доставка"),
                ),
                (
                    "is_partial_pickup_allowed",
                    models.BooleanField(
                        default=False, verbose_name="Можно забирать частично"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rents",
                        to="storage.box",
                        verbose_name="Арендуемый бокс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Арендатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аренда",
                "verbose_name_plural": "Аренды",
            },
        ),
    ]
