# Generated by Django 5.1.5 on 2025-01-22 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_rent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rent",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email клиента"
            ),
        ),
        migrations.AlterField(
            model_name="rent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Арендатор",
            ),
        ),
    ]
