# Generated by Django 5.1.5 on 2025-01-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0004_rent_email_alter_rent_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="rent",
            name="task_ids",
            field=models.JSONField(default=list, verbose_name="ID задач напоминаний"),
        ),
    ]
