# Generated by Django 5.1.5 on 2025-01-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_box_area'),
        ('storage', '0005_rent_task_ids'),
    ]

    operations = [
    ]
