# Generated by Django 5.1.5 on 2025-01-27 10:42

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0006_merge_0005_box_area_0005_rent_task_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="rent",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region="RU", verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="box",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Цена за месяц"
            ),
        ),
    ]
