# Generated by Django 5.1.5 on 2025-01-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0007_rent_phone_alter_box_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rent",
            name="is_delivery_needed",
            field=models.BooleanField(default=False, verbose_name="Нужна доставка"),
        ),
    ]
